name: music
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.6.2
  - pip:
    tqdm==4.32.1
    numpy==1.16.4
    louvain==0.7.0
    seaborn==0.9.0
    pandas==0.24.2
    statsmodels==0.10.0
    matplotlib==3.2.1
    scipy==1.4.1
    networkx==2.3
    ddot==0.4.0
    dill==0.3.4
    python_igraph==0.9.6
    scikit_learn==0.24.2
