name: music
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6.8
  - pip
  - pip:
    - dataclasses==0.8
    - louvain==0.6.1
    - decorator==4.4.2
    - dill==0.3.1.1
    - gensim==4.0.1
    - imutils==0.5.3
    - ndex-dev==3.0.11.41
    - networkx==1.11
    - numpy==1.19.5    
    - requests-toolbelt==0.9.1
    - scipy==1.2
    - smart-open==5.0.0
    - texttable==1.6.3
    - tulip-python==5.5.1